# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0004_spaceplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacesMembers',
            fields=[
                ('spaceplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spaces.SpacePlugin')),
            ],
            bases=('spaces.spaceplugin',),
        ),
    ]
